sudo: required

language: cpp

services:
  - docker

compiler:
  - gcc

jobs:
  include:
    - stage: test
      dist: trusty
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install build-essential cmake libboost-system-dev libboost-thread-dev libgtest-dev
        - cd /usr/src/gtest
        - sudo cmake CMakeLists.txt
        - sudo make
        - sudo cp *.a /usr/lib
      script:
        - cd ${TRAVIS_BUILD_DIR}
        - cmake --version
        - cmake .
        - make
        - make test
    - dist: xenial
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install build-essential cmake libboost-system-dev libboost-thread-dev libgtest-dev
        - cd /usr/src/gtest
        - sudo cmake CMakeLists.txt
        - sudo make
        - sudo cp *.a /usr/lib
      script:
        - cd ${TRAVIS_BUILD_DIR}
        - cmake --version
        - cmake .
        - make
        - make test
    - dist: xenial
      script:
        - sudo docker run -it --rm -v ${TRAVIS_BUILD_DIR}:/repo ubuntu:bionic /bin/bash -c "
          set -e
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get install build-essential cmake libboost-system-dev libboost-thread-dev libgtest-dev
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp *.a /usr/lib
          cd /repo
          cmake --version
          cmake .
          make
          make test"
